# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUBCFG_PAT: ${{ secrets.GITHUBCFG_PAT }}
      GITHUBCFG_NAMESPACE: ${{ secrets.GITHUBCFG_NAMESPACE }}
      GITHUBCFG_USERNAME: ${{ secrets.GITHUBCFG_USERNAME }}    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore ./DotNetApiEventBus/DotNetApiEventBus.slnx
    - name: Build
      run: dotnet build --no-restore ./DotNetApiEventBus/DotNetApiEventBus.slnx
    - name: Publish
      run: dotnet publish ./DotNetApiEventBus/DotNetApiEventBus.slnx
    - name: Test
      run: dotnet test --no-build --verbosity normal ./DotNetApiEventBus/DotNetApiEventBus.slnx
    - name: Create packages
      run: dotnet nuget push "DotNetApiEventBus/bin/Release/DotNetApiEventBus.3.0.3.nupkg" --api-key $GITHUBCFG_PAT --source "github" --skip-duplicate